import { StyleSheet } from 'react-native';
import {
  Colors,
  FontFamily,
  FontSizes,
  BorderRadius,
  Spacing,
  TextStyles,
} from '../../constants/theme';

/**
 * Shared styles used across all EventCreate step components.
 * Extracted from the original EventCreateScreen to maintain visual consistency.
 */
const styles = StyleSheet.create({
  stepContent: {
    padding: Spacing.lg,
    gap: Spacing.lg,
  },
  // Section heading — editorial display, bigger + tighter tracking
  stepTitle: {
    fontFamily: FontFamily.displayExtraBold,
    fontSize: 30,
    lineHeight: 32,
    letterSpacing: -0.9,
    color: Colors.gray900,
    marginBottom: Spacing.xs,
  },
  stepDescription: {
    fontFamily: FontFamily.regular,
    fontSize: FontSizes.sm,
    lineHeight: 22,
    color: Colors.gray500,
    marginBottom: Spacing.lg,
    maxWidth: '92%',
  },
  // Editorial eyebrow — sits above stepTitle. New token for progressive adoption.
  stepEyebrow: {
    fontFamily: FontFamily.bold,
    fontSize: 10,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: Colors.gray500,
    marginBottom: Spacing.xs,
  },
  inputGroup: {
    marginBottom: Spacing.lg,
  },
  // Uppercase micro-label, bold, letter-spaced (editorial hierarchy)
  label: {
    fontFamily: FontFamily.bold,
    fontSize: 10,
    color: Colors.gray600,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
    marginBottom: Spacing.sm,
  },
  // Label row: uppercase label on left + char counter / action on right
  labelRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  labelRowLabel: {
    fontFamily: FontFamily.bold,
    fontSize: 10,
    color: Colors.gray600,
    textTransform: 'uppercase',
    letterSpacing: 1.4,
  },
  labelRowCounter: {
    fontFamily: FontFamily.medium,
    fontSize: 11,
    color: Colors.gray400,
  },
  input: {
    backgroundColor: Colors.white,
    borderRadius: BorderRadius.xl,
    paddingHorizontal: Spacing.base,
    paddingVertical: 14,
    fontFamily: FontFamily.regular,
    fontSize: FontSizes.base,
    color: Colors.gray900,
    borderWidth: 1,
    borderColor: Colors.gray100,
  },
  // Prominent display-font title input — editorial headline field
  inputTitle: {
    fontFamily: FontFamily.displayBold,
    fontSize: 26,
    letterSpacing: -0.8,
    lineHeight: 30,
    paddingVertical: 18,
  },
  inputWithAction: {
    paddingRight: 44,
  },
  inputInlineAction: {
    position: 'absolute',
    right: 6,
    top: 6,
    bottom: 6,
    width: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: BorderRadius.md,
  },
  textArea: {
    minHeight: 120,
    paddingTop: 14,
    textAlignVertical: 'top',
  },
  textAreaSmall: {
    minHeight: 80,
    paddingTop: 14,
    textAlignVertical: 'top',
  },
  charCount: {
    fontFamily: FontFamily.medium,
    fontSize: 11,
    color: Colors.gray400,
    textAlign: 'right',
    marginTop: Spacing.xs,
  },
  inputHint: {
    fontFamily: FontFamily.regular,
    fontSize: FontSizes.xs,
    color: Colors.gray500,
    lineHeight: 16,
    marginTop: Spacing.xs,
  },
  imagePickerButton: {
    borderRadius: BorderRadius['4xl'],
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: Colors.gray200,
    borderStyle: 'dashed',
  },
  imagePickerPlaceholder: {
    minHeight: 200,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.md,
    padding: Spacing.lg,
    backgroundColor: Colors.gray50,
  },
  // Floating white circle housing the upload icon (Eventbrite-style hero zone)
  imagePickerIconBubble: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  imagePickerTextGroup: {
    alignItems: 'center',
    gap: 2,
  },
  imagePickerText: {
    fontFamily: FontFamily.semiBold,
    fontSize: FontSizes.sm,
    color: Colors.gray900,
  },
  imagePickerSubtext: {
    fontFamily: FontFamily.regular,
    fontSize: FontSizes.xs,
    color: Colors.gray500,
  },
  imagePreviewContainer: {
    position: 'relative',
  },
  imagePreview: {
    width: '100%',
    height: 160,
  },
  removeImageButton: {
    position: 'absolute',
    top: Spacing.sm,
    right: Spacing.sm,
    backgroundColor: Colors.white,
    borderRadius: 12,
  },
  typeSelector: {
    flexDirection: 'row',
    gap: Spacing.md,
  },
  typeOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.gray100,
    borderWidth: 1,
    borderColor: Colors.gray200,
  },
  typeOptionActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  typeOptionText: {
    fontFamily: FontFamily.medium,
    fontSize: FontSizes.sm,
    color: Colors.gray600,
  },
  typeOptionTextActive: {
    color: Colors.white,
  },
  categoriesContainer: {
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingVertical: Spacing.xs,
  },
  categoryChip: {
    paddingHorizontal: Spacing.base,
    paddingVertical: 9,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.gray200,
  },
  // Active chip: solid indigo with a soft shadow (matches redesign mock)
  categoryChipActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 3,
  },
  categoryChipText: {
    fontFamily: FontFamily.semiBold,
    fontSize: 13,
    color: Colors.gray600,
  },
  categoryChipTextActive: {
    color: Colors.white,
    fontFamily: FontFamily.bold,
  },
  locationTypeSelector: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  locationTypeOption: {
    flex: 1,
    alignItems: 'center',
    padding: Spacing.md,
    borderRadius: BorderRadius.lg,
    backgroundColor: Colors.gray50,
    borderWidth: 1,
    borderColor: Colors.gray200,
  },
  locationTypeOptionActive: {
    backgroundColor: Colors.primaryBg,
    borderColor: Colors.primary,
  },
  locationTypeLabel: {
    fontFamily: FontFamily.medium,
    fontSize: FontSizes.sm,
    color: Colors.gray700,
    marginTop: Spacing.xs,
  },
  locationTypeLabelActive: {
    color: Colors.primary,
  },
  locationTypeDesc: {
    fontFamily: FontFamily.regular,
    fontSize: FontSizes.xs,
    color: Colors.gray500,
    textAlign: 'center',
    marginTop: 2,
  },
  locationFields: {
    marginTop: Spacing.lg,
    paddingTop: Spacing.lg,
    borderTopWidth: 1,
    borderTopColor: Colors.gray100,
  },
  subSectionTitle: {
    ...TextStyles.bodyBold,
    color: Colors.gray800,
    marginBottom: Spacing.md,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: Spacing.md,
    marginBottom: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray100,
  },
  switchContent: {
    flex: 1,
    marginRight: Spacing.md,
  },
  switchLabel: {
    fontFamily: FontFamily.medium,
    fontSize: FontSizes.base,
    color: Colors.gray900,
  },
  switchDescription: {
    fontFamily: FontFamily.regular,
    fontSize: FontSizes.sm,
    color: Colors.gray500,
    marginTop: 2,
    lineHeight: 18,
  },
  mapPickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.gray50,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.gray200,
    gap: Spacing.sm,
  },
  mapPickerButtonText: {
    flex: 1,
    fontFamily: FontFamily.medium,
    fontSize: FontSizes.base,
    color: Colors.primary,
  },
  selectedCoordsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    marginTop: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    backgroundColor: Colors.successLight,
    borderRadius: BorderRadius.md,
  },
  selectedCoordsText: {
    fontFamily: FontFamily.medium,
    fontSize: FontSizes.sm,
    color: Colors.successDark,
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: Colors.primaryBg,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginBottom: Spacing.lg,
    gap: Spacing.sm,
  },
  infoBoxText: {
    flex: 1,
    fontFamily: FontFamily.medium,
    fontSize: FontSizes.sm,
    color: Colors.primary,
    lineHeight: 20,
  },
  warningInfoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: Colors.warningLight,
    borderRadius: BorderRadius.lg,
    padding: Spacing.md,
    marginTop: Spacing.md,
    gap: Spacing.sm,
  },
  warningInfoBoxText: {
    flex: 1,
    fontFamily: FontFamily.medium,
    fontSize: FontSizes.sm,
    color: Colors.warningDark,
    lineHeight: 20,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: Spacing['3xl'],
    backgroundColor: Colors.gray50,
    borderRadius: BorderRadius.lg,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: Colors.gray200,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: Colors.gray100,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.md,
  },
  emptyTitle: {
    fontFamily: FontFamily.semiBold,
    fontSize: FontSizes.base,
    color: Colors.gray700,
    marginBottom: Spacing.xs,
  },
  emptyText: {
    fontFamily: FontFamily.regular,
    fontSize: FontSizes.sm,
    lineHeight: 20,
    color: Colors.gray500,
    marginBottom: Spacing.lg,
    textAlign: 'center',
    paddingHorizontal: Spacing.lg,
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primary,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
    borderRadius: BorderRadius['2xl'],
    gap: Spacing.sm,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.22,
    shadowRadius: 10,
    elevation: 3,
  },
  addButtonText: {
    fontFamily: FontFamily.bold,
    fontSize: FontSizes.sm,
    color: Colors.white,
    letterSpacing: -0.1,
  },
  card: {
    backgroundColor: Colors.card,
    borderRadius: BorderRadius['2xl'],
    padding: Spacing.base,
    marginBottom: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.gray100,
    shadowColor: '#4F46E5',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
    paddingBottom: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray100,
  },
  cardTitle: {
    fontFamily: FontFamily.displaySemiBold,
    fontSize: FontSizes.lg,
    letterSpacing: -0.3,
    color: Colors.gray900,
  },
  chipContainer: {
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingVertical: Spacing.xs,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.base,
    paddingVertical: 8,
    borderRadius: BorderRadius.full,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.gray200,
  },
  chipActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 2,
  },
  chipText: {
    fontFamily: FontFamily.semiBold,
    fontSize: 13,
    color: Colors.gray600,
  },
  chipTextActive: {
    color: Colors.white,
    fontFamily: FontFamily.bold,
  },
  // Dashed "+ Add" chip for custom tags
  chipDashed: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    borderRadius: BorderRadius.full,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: Colors.gray300,
    backgroundColor: 'transparent',
  },
  chipDashedText: {
    fontFamily: FontFamily.medium,
    fontSize: 13,
    color: Colors.gray500,
  },
  addAnotherButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: Colors.gray200,
    backgroundColor: Colors.gray50,
    gap: Spacing.sm,
  },
  addAnotherText: {
    fontFamily: FontFamily.semiBold,
    fontSize: FontSizes.sm,
    color: Colors.primary,
    letterSpacing: -0.1,
  },
  summaryCard: {
    backgroundColor: Colors.gray50,
    borderRadius: BorderRadius.lg,
    padding: Spacing.lg,
    marginTop: Spacing.lg,
  },
  summaryTitle: {
    ...TextStyles.bodyBold,
    marginBottom: Spacing.md,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray200,
  },
  summaryLabel: {
    fontFamily: FontFamily.regular,
    fontSize: FontSizes.sm,
    color: Colors.gray500,
  },
  summaryValue: {
    fontFamily: FontFamily.medium,
    fontSize: FontSizes.sm,
    color: Colors.gray900,
    maxWidth: '60%',
    textAlign: 'right',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    marginBottom: Spacing.md,
  },
  sectionIconContainer: {
    width: 40,
    height: 40,
    borderRadius: BorderRadius.xl,
    backgroundColor: Colors.primaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionHeaderTitle: {
    fontFamily: FontFamily.displaySemiBold,
    fontSize: FontSizes.xl,
    letterSpacing: -0.4,
    color: Colors.gray900,
  },
  sectionHeaderDescription: {
    fontFamily: FontFamily.regular,
    fontSize: FontSizes.sm,
    lineHeight: 18,
    color: Colors.gray500,
    marginTop: 2,
  },
  sectionDivider: {
    paddingTop: Spacing.lg,
    borderTopWidth: 1,
    borderTopColor: Colors.gray200,
  },
  advancedToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.gray50,
    borderRadius: BorderRadius.lg,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
    borderWidth: 1,
    borderColor: Colors.gray200,
  },
  advancedToggleText: {
    fontFamily: FontFamily.medium,
    fontSize: FontSizes.sm,
    color: Colors.gray700,
  },
  advancedContent: {
    marginTop: Spacing.md,
  },
  // Option card grid — used for visibility / any "3 choice" card selector
  optionCardRow: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
  },
  optionCard: {
    flex: 1,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.sm,
    borderRadius: BorderRadius['2xl'],
    borderWidth: 1.5,
    borderColor: Colors.gray200,
    backgroundColor: Colors.card,
    alignItems: 'center',
    gap: 6,
  },
  optionCardActive: {
    borderColor: Colors.primary,
    backgroundColor: Colors.primaryBg,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 2,
  },
  optionCardIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.gray100,
  },
  optionCardIconWrapActive: {
    backgroundColor: Colors.primary,
  },
  optionCardLabel: {
    fontFamily: FontFamily.semiBold,
    fontSize: 12.5,
    color: Colors.gray800,
    letterSpacing: -0.1,
    textAlign: 'center',
  },
  optionCardLabelActive: {
    color: Colors.primary,
    fontFamily: FontFamily.bold,
  },
  optionCardDesc: {
    fontFamily: FontFamily.regular,
    fontSize: 10.5,
    lineHeight: 14,
    color: Colors.gray500,
    textAlign: 'center',
  },
  optionCardDescActive: {
    color: Colors.primary,
  },
});

export default styles;
